[platformio]
default_envs = m5stack-cores3

[env:m5stack-cores3]
platform = espressif32@7.0.1
board = m5stack-cores3
framework = espidf
monitor_speed = 115200
board_build.sdkconfig = sdkconfig.defaults

